-- Users table
CREATE TABLE movie_users (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(100) NOT NULL UNIQUE,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Watchlist table
CREATE TABLE watchlist (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER NOT NULL,
    movie_id      NUMBER NOT NULL,
    watched_yn    CHAR(1) DEFAULT 'N',
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_watchlist_user 
        FOREIGN KEY (user_id) REFERENCES movie_users(id),
    CONSTRAINT uq_watchlist UNIQUE (user_id, movie_id)
);